import { CountryCode } from "libphonenumber-js";

export interface CountryOption {
  code: string;
  iso2: CountryCode;
  name: string;
  flag: string;
}

// Generate country flag emojis from ISO-3166-1 alpha-2 code
export function getFlagEmoji(countryCode: string): string {
  const codePoints = countryCode
    .toUpperCase()
    .split("")
    .map((char) => 127397 + char.charCodeAt(0));
  try {
    return String.fromCodePoint(...codePoints);
  } catch {
    return "🌐";
  }
}

export const ALL_COUNTRIES: CountryOption[] = [
  { name: "Afghanistan", iso2: "AF", code: "+93", flag: getFlagEmoji("AF") },
  { name: "Albania", iso2: "AL", code: "+355", flag: getFlagEmoji("AL") },
  { name: "Algeria", iso2: "DZ", code: "+213", flag: getFlagEmoji("DZ") },
  { name: "Andorra", iso2: "AD", code: "+376", flag: getFlagEmoji("AD") },
  { name: "Angola", iso2: "AO", code: "+244", flag: getFlagEmoji("AO") },
  { name: "Antigua and Barbuda", iso2: "AG", code: "+1", flag: getFlagEmoji("AG") },
  { name: "Argentina", iso2: "AR", code: "+54", flag: getFlagEmoji("AR") },
  { name: "Armenia", iso2: "AM", code: "+374", flag: getFlagEmoji("AM") },
  { name: "Australia", iso2: "AU", code: "+61", flag: getFlagEmoji("AU") },
  { name: "Austria", iso2: "AT", code: "+43", flag: getFlagEmoji("AT") },
  { name: "Azerbaijan", iso2: "AZ", code: "+994", flag: getFlagEmoji("AZ") },
  { name: "Bahamas", iso2: "BS", code: "+1", flag: getFlagEmoji("BS") },
  { name: "Bahrain", iso2: "BH", code: "+973", flag: getFlagEmoji("BH") },
  { name: "Bangladesh", iso2: "BD", code: "+880", flag: getFlagEmoji("BD") },
  { name: "Barbados", iso2: "BB", code: "+1", flag: getFlagEmoji("BB") },
  { name: "Belarus", iso2: "BY", code: "+375", flag: getFlagEmoji("BY") },
  { name: "Belgium", iso2: "BE", code: "+32", flag: getFlagEmoji("BE") },
  { name: "Belize", iso2: "BZ", code: "+501", flag: getFlagEmoji("BZ") },
  { name: "Benin", iso2: "BJ", code: "+229", flag: getFlagEmoji("BJ") },
  { name: "Bhutan", iso2: "BT", code: "+975", flag: getFlagEmoji("BT") },
  { name: "Bolivia", iso2: "BO", code: "+591", flag: getFlagEmoji("BO") },
  { name: "Bosnia and Herzegovina", iso2: "BA", code: "+387", flag: getFlagEmoji("BA") },
  { name: "Botswana", iso2: "BW", code: "+267", flag: getFlagEmoji("BW") },
  { name: "Brazil", iso2: "BR", code: "+55", flag: getFlagEmoji("BR") },
  { name: "Brunei", iso2: "BN", code: "+673", flag: getFlagEmoji("BN") },
  { name: "Bulgaria", iso2: "BG", code: "+359", flag: getFlagEmoji("BG") },
  { name: "Burkina Faso", iso2: "BF", code: "+226", flag: getFlagEmoji("BF") },
  { name: "Burundi", iso2: "BI", code: "+257", flag: getFlagEmoji("BI") },
  { name: "Cambodia", iso2: "KH", code: "+855", flag: getFlagEmoji("KH") },
  { name: "Cameroon", iso2: "CM", code: "+237", flag: getFlagEmoji("CM") },
  { name: "Canada", iso2: "CA", code: "+1", flag: getFlagEmoji("CA") },
  { name: "Cape Verde", iso2: "CV", code: "+238", flag: getFlagEmoji("CV") },
  { name: "Central African Republic", iso2: "CF", code: "+236", flag: getFlagEmoji("CF") },
  { name: "Chad", iso2: "TD", code: "+235", flag: getFlagEmoji("TD") },
  { name: "Chile", iso2: "CL", code: "+56", flag: getFlagEmoji("CL") },
  { name: "China", iso2: "CN", code: "+86", flag: getFlagEmoji("CN") },
  { name: "Colombia", iso2: "CO", code: "+57", flag: getFlagEmoji("CO") },
  { name: "Comoros", iso2: "KM", code: "+269", flag: getFlagEmoji("KM") },
  { name: "Congo (Brazzaville)", iso2: "CG", code: "+242", flag: getFlagEmoji("CG") },
  { name: "Congo (Kinshasa)", iso2: "CD", code: "+243", flag: getFlagEmoji("CD") },
  { name: "Costa Rica", iso2: "CR", code: "+506", flag: getFlagEmoji("CR") },
  { name: "Croatia", iso2: "HR", code: "+385", flag: getFlagEmoji("HR") },
  { name: "Cuba", iso2: "CU", code: "+53", flag: getFlagEmoji("CU") },
  { name: "Cyprus", iso2: "CY", code: "+357", flag: getFlagEmoji("CY") },
  { name: "Czech Republic", iso2: "CZ", code: "+420", flag: getFlagEmoji("CZ") },
  { name: "Denmark", iso2: "DK", code: "+45", flag: getFlagEmoji("DK") },
  { name: "Djibouti", iso2: "DJ", code: "+253", flag: getFlagEmoji("DJ") },
  { name: "Dominica", iso2: "DM", code: "+1", flag: getFlagEmoji("DM") },
  { name: "Dominican Republic", iso2: "DO", code: "+1", flag: getFlagEmoji("DO") },
  { name: "Ecuador", iso2: "EC", code: "+593", flag: getFlagEmoji("EC") },
  { name: "Egypt", iso2: "EG", code: "+20", flag: getFlagEmoji("EG") },
  { name: "El Salvador", iso2: "SV", code: "+503", flag: getFlagEmoji("SV") },
  { name: "Equatorial Guinea", iso2: "GQ", code: "+240", flag: getFlagEmoji("GQ") },
  { name: "Eritrea", iso2: "ER", code: "+291", flag: getFlagEmoji("ER") },
  { name: "Estonia", iso2: "EE", code: "+372", flag: getFlagEmoji("EE") },
  { name: "Ethiopia", iso2: "ET", code: "+251", flag: getFlagEmoji("ET") },
  { name: "Fiji", iso2: "FJ", code: "+679", flag: getFlagEmoji("FJ") },
  { name: "Finland", iso2: "FI", code: "+358", flag: getFlagEmoji("FI") },
  { name: "France", iso2: "FR", code: "+33", flag: getFlagEmoji("FR") },
  { name: "Gabon", iso2: "GA", code: "+241", flag: getFlagEmoji("GA") },
  { name: "Gambia", iso2: "GM", code: "+220", flag: getFlagEmoji("GM") },
  { name: "Georgia", iso2: "GE", code: "+995", flag: getFlagEmoji("GE") },
  { name: "Germany", iso2: "DE", code: "+49", flag: getFlagEmoji("DE") },
  { name: "Ghana", iso2: "GH", code: "+233", flag: getFlagEmoji("GH") },
  { name: "Greece", iso2: "GR", code: "+30", flag: getFlagEmoji("GR") },
  { name: "Grenada", iso2: "GD", code: "+1", flag: getFlagEmoji("GD") },
  { name: "Guatemala", iso2: "GT", code: "+502", flag: getFlagEmoji("GT") },
  { name: "Guinea", iso2: "GN", code: "+224", flag: getFlagEmoji("GN") },
  { name: "Guinea-Bissau", iso2: "GW", code: "+245", flag: getFlagEmoji("GW") },
  { name: "Guyana", iso2: "GY", code: "+592", flag: getFlagEmoji("GY") },
  { name: "Haiti", iso2: "HT", code: "+509", flag: getFlagEmoji("HT") },
  { name: "Honduras", iso2: "HN", code: "+504", flag: getFlagEmoji("HN") },
  { name: "Hong Kong", iso2: "HK", code: "+852", flag: getFlagEmoji("HK") },
  { name: "Hungary", iso2: "HU", code: "+36", flag: getFlagEmoji("HU") },
  { name: "Iceland", iso2: "IS", code: "+354", flag: getFlagEmoji("IS") },
  { name: "India", iso2: "IN", code: "+91", flag: getFlagEmoji("IN") },
  { name: "Indonesia", iso2: "ID", code: "+62", flag: getFlagEmoji("ID") },
  { name: "Iran", iso2: "IR", code: "+98", flag: getFlagEmoji("IR") },
  { name: "Iraq", iso2: "IQ", code: "+964", flag: getFlagEmoji("IQ") },
  { name: "Ireland", iso2: "IE", code: "+353", flag: getFlagEmoji("IE") },
  { name: "Israel", iso2: "IL", code: "+972", flag: getFlagEmoji("IL") },
  { name: "Italy", iso2: "IT", code: "+39", flag: getFlagEmoji("IT") },
  { name: "Ivory Coast", iso2: "CI", code: "+225", flag: getFlagEmoji("CI") },
  { name: "Jamaica", iso2: "JM", code: "+1", flag: getFlagEmoji("JM") },
  { name: "Japan", iso2: "JP", code: "+81", flag: getFlagEmoji("JP") },
  { name: "Jordan", iso2: "JO", code: "+962", flag: getFlagEmoji("JO") },
  { name: "Kazakhstan", iso2: "KZ", code: "+7", flag: getFlagEmoji("KZ") },
  { name: "Kenya", iso2: "KE", code: "+254", flag: getFlagEmoji("KE") },
  { name: "Kiribati", iso2: "KI", code: "+686", flag: getFlagEmoji("KI") },
  { name: "Kuwait", iso2: "KW", code: "+965", flag: getFlagEmoji("KW") },
  { name: "Kyrgyzstan", iso2: "KG", code: "+996", flag: getFlagEmoji("KG") },
  { name: "Laos", iso2: "LA", code: "+856", flag: getFlagEmoji("LA") },
  { name: "Latvia", iso2: "LV", code: "+371", flag: getFlagEmoji("LV") },
  { name: "Lebanon", iso2: "LB", code: "+961", flag: getFlagEmoji("LB") },
  { name: "Lesotho", iso2: "LS", code: "+266", flag: getFlagEmoji("LS") },
  { name: "Liberia", iso2: "LR", code: "+231", flag: getFlagEmoji("LR") },
  { name: "Libya", iso2: "LY", code: "+218", flag: getFlagEmoji("LY") },
  { name: "Liechtenstein", iso2: "LI", code: "+423", flag: getFlagEmoji("LI") },
  { name: "Lithuania", iso2: "LT", code: "+370", flag: getFlagEmoji("LT") },
  { name: "Luxembourg", iso2: "LU", code: "+352", flag: getFlagEmoji("LU") },
  { name: "Macau", iso2: "MO", code: "+853", flag: getFlagEmoji("MO") },
  { name: "Macedonia", iso2: "MK", code: "+389", flag: getFlagEmoji("MK") },
  { name: "Madagascar", iso2: "MG", code: "+261", flag: getFlagEmoji("MG") },
  { name: "Malawi", iso2: "MW", code: "+265", flag: getFlagEmoji("MW") },
  { name: "Malaysia", iso2: "MY", code: "+60", flag: getFlagEmoji("MY") },
  { name: "Maldives", iso2: "MV", code: "+960", flag: getFlagEmoji("MV") },
  { name: "Mali", iso2: "ML", code: "+223", flag: getFlagEmoji("ML") },
  { name: "Malta", iso2: "MT", code: "+356", flag: getFlagEmoji("MT") },
  { name: "Marshall Islands", iso2: "MH", code: "+692", flag: getFlagEmoji("MH") },
  { name: "Mauritania", iso2: "MR", code: "+222", flag: getFlagEmoji("MR") },
  { name: "Mauritius", iso2: "MU", code: "+230", flag: getFlagEmoji("MU") },
  { name: "Mexico", iso2: "MX", code: "+52", flag: getFlagEmoji("MX") },
  { name: "Micronesia", iso2: "FM", code: "+691", flag: getFlagEmoji("FM") },
  { name: "Moldova", iso2: "MD", code: "+373", flag: getFlagEmoji("MD") },
  { name: "Monaco", iso2: "MC", code: "+377", flag: getFlagEmoji("MC") },
  { name: "Mongolia", iso2: "MN", code: "+976", flag: getFlagEmoji("MN") },
  { name: "Montenegro", iso2: "ME", code: "+382", flag: getFlagEmoji("ME") },
  { name: "Morocco", iso2: "MA", code: "+212", flag: getFlagEmoji("MA") },
  { name: "Mozambique", iso2: "MZ", code: "+258", flag: getFlagEmoji("MZ") },
  { name: "Myanmar", iso2: "MM", code: "+95", flag: getFlagEmoji("MM") },
  { name: "Namibia", iso2: "NA", code: "+264", flag: getFlagEmoji("NA") },
  { name: "Nauru", iso2: "NR", code: "+674", flag: getFlagEmoji("NR") },
  { name: "Nepal", iso2: "NP", code: "+977", flag: getFlagEmoji("NP") },
  { name: "Netherlands", iso2: "NL", code: "+31", flag: getFlagEmoji("NL") },
  { name: "New Zealand", iso2: "NZ", code: "+64", flag: getFlagEmoji("NZ") },
  { name: "Nicaragua", iso2: "NI", code: "+505", flag: getFlagEmoji("NI") },
  { name: "Niger", iso2: "NE", code: "+227", flag: getFlagEmoji("NE") },
  { name: "Nigeria", iso2: "NG", code: "+234", flag: getFlagEmoji("NG") },
  { name: "North Korea", iso2: "KP", code: "+850", flag: getFlagEmoji("KP") },
  { name: "Norway", iso2: "NO", code: "+47", flag: getFlagEmoji("NO") },
  { name: "Oman", iso2: "OM", code: "+968", flag: getFlagEmoji("OM") },
  { name: "Pakistan", iso2: "PK", code: "+92", flag: getFlagEmoji("PK") },
  { name: "Palau", iso2: "PW", code: "+680", flag: getFlagEmoji("PW") },
  { name: "Palestine", iso2: "PS", code: "+970", flag: getFlagEmoji("PS") },
  { name: "Panama", iso2: "PA", code: "+507", flag: getFlagEmoji("PA") },
  { name: "Papua New Guinea", iso2: "PG", code: "+675", flag: getFlagEmoji("PG") },
  { name: "Paraguay", iso2: "PY", code: "+595", flag: getFlagEmoji("PY") },
  { name: "Peru", iso2: "PE", code: "+51", flag: getFlagEmoji("PE") },
  { name: "Philippines", iso2: "PH", code: "+63", flag: getFlagEmoji("PH") },
  { name: "Poland", iso2: "PL", code: "+48", flag: getFlagEmoji("PL") },
  { name: "Portugal", iso2: "PT", code: "+351", flag: getFlagEmoji("PT") },
  { name: "Qatar", iso2: "QA", code: "+974", flag: getFlagEmoji("QA") },
  { name: "Romania", iso2: "RO", code: "+40", flag: getFlagEmoji("RO") },
  { name: "Russia", iso2: "RU", code: "+7", flag: getFlagEmoji("RU") },
  { name: "Rwanda", iso2: "RW", code: "+250", flag: getFlagEmoji("RW") },
  { name: "Saint Kitts and Nevis", iso2: "KN", code: "+1", flag: getFlagEmoji("KN") },
  { name: "Saint Lucia", iso2: "LC", code: "+1", flag: getFlagEmoji("LC") },
  { name: "Saint Vincent and the Grenadines", iso2: "VC", code: "+1", flag: getFlagEmoji("VC") },
  { name: "Samoa", iso2: "WS", code: "+685", flag: getFlagEmoji("WS") },
  { name: "San Marino", iso2: "SM", code: "+378", flag: getFlagEmoji("SM") },
  { name: "Sao Tome and Principe", iso2: "ST", code: "+239", flag: getFlagEmoji("ST") },
  { name: "Saudi Arabia", iso2: "SA", code: "+966", flag: getFlagEmoji("SA") },
  { name: "Senegal", iso2: "SN", code: "+221", flag: getFlagEmoji("SN") },
  { name: "Serbia", iso2: "RS", code: "+381", flag: getFlagEmoji("RS") },
  { name: "Seychelles", iso2: "SC", code: "+248", flag: getFlagEmoji("SC") },
  { name: "Sierra Leone", iso2: "SL", code: "+232", flag: getFlagEmoji("SL") },
  { name: "Singapore", iso2: "SG", code: "+65", flag: getFlagEmoji("SG") },
  { name: "Slovakia", iso2: "SK", code: "+421", flag: getFlagEmoji("SK") },
  { name: "Slovenia", iso2: "SI", code: "+386", flag: getFlagEmoji("SI") },
  { name: "Solomon Islands", iso2: "SB", code: "+677", flag: getFlagEmoji("SB") },
  { name: "Somalia", iso2: "SO", code: "+252", flag: getFlagEmoji("SO") },
  { name: "South Africa", iso2: "ZA", code: "+27", flag: getFlagEmoji("ZA") },
  { name: "South Korea", iso2: "KR", code: "+82", flag: getFlagEmoji("KR") },
  { name: "South Sudan", iso2: "SS", code: "+211", flag: getFlagEmoji("SS") },
  { name: "Spain", iso2: "ES", code: "+34", flag: getFlagEmoji("ES") },
  { name: "Sri Lanka", iso2: "LK", code: "+94", flag: getFlagEmoji("LK") },
  { name: "Sudan", iso2: "SD", code: "+249", flag: getFlagEmoji("SD") },
  { name: "Suriname", iso2: "SR", code: "+597", flag: getFlagEmoji("SR") },
  { name: "Swaziland", iso2: "SZ", code: "+268", flag: getFlagEmoji("SZ") },
  { name: "Sweden", iso2: "SE", code: "+46", flag: getFlagEmoji("SE") },
  { name: "Switzerland", iso2: "CH", code: "+41", flag: getFlagEmoji("CH") },
  { name: "Syria", iso2: "SY", code: "+963", flag: getFlagEmoji("SY") },
  { name: "Taiwan", iso2: "TW", code: "+886", flag: getFlagEmoji("TW") },
  { name: "Tajikistan", iso2: "TJ", code: "+992", flag: getFlagEmoji("TJ") },
  { name: "Tanzania", iso2: "TZ", code: "+255", flag: getFlagEmoji("TZ") },
  { name: "Thailand", iso2: "TH", code: "+66", flag: getFlagEmoji("TH") },
  { name: "Timor-Leste", iso2: "TL", code: "+670", flag: getFlagEmoji("TL") },
  { name: "Togo", iso2: "TG", code: "+228", flag: getFlagEmoji("TG") },
  { name: "Tonga", iso2: "TO", code: "+676", flag: getFlagEmoji("TO") },
  { name: "Trinidad and Tobago", iso2: "TT", code: "+1", flag: getFlagEmoji("TT") },
  { name: "Tunisia", iso2: "TN", code: "+216", flag: getFlagEmoji("TN") },
  { name: "Turkey", iso2: "TR", code: "+90", flag: getFlagEmoji("TR") },
  { name: "Turkmenistan", iso2: "TM", code: "+993", flag: getFlagEmoji("TM") },
  { name: "Tuvalu", iso2: "TV", code: "+688", flag: getFlagEmoji("TV") },
  { name: "Uganda", iso2: "UG", code: "+256", flag: getFlagEmoji("UG") },
  { name: "Ukraine", iso2: "UA", code: "+380", flag: getFlagEmoji("UA") },
  { name: "United Arab Emirates", iso2: "AE", code: "+971", flag: getFlagEmoji("AE") },
  { name: "United Kingdom", iso2: "GB", code: "+44", flag: getFlagEmoji("GB") },
  { name: "United States", iso2: "US", code: "+1", flag: getFlagEmoji("US") },
  { name: "Uruguay", iso2: "UY", code: "+598", flag: getFlagEmoji("UY") },
  { name: "Uzbekistan", iso2: "UZ", code: "+998", flag: getFlagEmoji("UZ") },
  { name: "Vanuatu", iso2: "VU", code: "+678", flag: getFlagEmoji("VU") },
  { name: "Vatican City", iso2: "VA", code: "+39", flag: getFlagEmoji("VA") },
  { name: "Venezuela", iso2: "VE", code: "+58", flag: getFlagEmoji("VE") },
  { name: "Vietnam", iso2: "VN", code: "+84", flag: getFlagEmoji("VN") },
  { name: "Yemen", iso2: "YE", code: "+967", flag: getFlagEmoji("YE") },
  { name: "Zambia", iso2: "ZM", code: "+260", flag: getFlagEmoji("ZM") },
  { name: "Zimbabwe", iso2: "ZW", code: "+263", flag: getFlagEmoji("ZW") },
];
